import type {
  BacktestSummary,
  Game,
  GameLog,
  LineQuote,
  Player,
  PropDetail,
  PropMarket,
  Team,
} from "./types";

export const teams: Record<string, Team> = {
  KC: {
    abbreviation: "KC",
    name: "Chiefs",
    city: "Kansas City",
    conference: "AFC",
    division: "West",
    primary: "#e31837",
    secondary: "#ffb612",
  },
  BUF: {
    abbreviation: "BUF",
    name: "Bills",
    city: "Buffalo",
    conference: "AFC",
    division: "East",
    primary: "#00338d",
    secondary: "#c60c30",
  },
  SF: {
    abbreviation: "SF",
    name: "49ers",
    city: "San Francisco",
    conference: "NFC",
    division: "West",
    primary: "#aa0000",
    secondary: "#b3995d",
  },
  SEA: {
    abbreviation: "SEA",
    name: "Seahawks",
    city: "Seattle",
    conference: "NFC",
    division: "West",
    primary: "#002244",
    secondary: "#69be28",
  },
  PHI: {
    abbreviation: "PHI",
    name: "Eagles",
    city: "Philadelphia",
    conference: "NFC",
    division: "East",
    primary: "#004c54",
    secondary: "#a5acaf",
  },
  DAL: {
    abbreviation: "DAL",
    name: "Cowboys",
    city: "Dallas",
    conference: "NFC",
    division: "East",
    primary: "#003594",
    secondary: "#869397",
  },
  CIN: {
    abbreviation: "CIN",
    name: "Bengals",
    city: "Cincinnati",
    conference: "AFC",
    division: "North",
    primary: "#fb4f14",
    secondary: "#000000",
  },
  BAL: {
    abbreviation: "BAL",
    name: "Ravens",
    city: "Baltimore",
    conference: "AFC",
    division: "North",
    primary: "#241773",
    secondary: "#9e7c0c",
  },
  DET: {
    abbreviation: "DET",
    name: "Lions",
    city: "Detroit",
    conference: "NFC",
    division: "North",
    primary: "#0076b6",
    secondary: "#b0b7bc",
  },
  MIN: {
    abbreviation: "MIN",
    name: "Vikings",
    city: "Minnesota",
    conference: "NFC",
    division: "North",
    primary: "#4f2683",
    secondary: "#ffc62f",
  },
};

export const games: Game[] = [
  {
    id: "kc-at-buf",
    season: 2025,
    week: 11,
    kickoff: "2025-11-16T18:00:00Z",
    homeTeamAbbr: "BUF",
    awayTeamAbbr: "KC",
    spread: -2.5,
    total: 48.5,
  },
  {
    id: "sf-at-sea",
    season: 2025,
    week: 11,
    kickoff: "2025-11-16T21:25:00Z",
    homeTeamAbbr: "SEA",
    awayTeamAbbr: "SF",
    spread: 1.5,
    total: 44.0,
  },
  {
    id: "phi-at-dal",
    season: 2025,
    week: 11,
    kickoff: "2025-11-16T21:25:00Z",
    homeTeamAbbr: "DAL",
    awayTeamAbbr: "PHI",
    spread: -3.0,
    total: 47.5,
  },
  {
    id: "cin-at-bal",
    season: 2025,
    week: 11,
    kickoff: "2025-11-16T18:00:00Z",
    homeTeamAbbr: "BAL",
    awayTeamAbbr: "CIN",
    spread: -4.0,
    total: 49.5,
  },
  {
    id: "det-at-min",
    season: 2025,
    week: 11,
    kickoff: "2025-11-14T01:15:00Z",
    homeTeamAbbr: "MIN",
    awayTeamAbbr: "DET",
    spread: 3.0,
    total: 51.0,
  },
];

export const players: Player[] = [
  { id: "mahomes", fullName: "Patrick Mahomes", position: "QB", jersey: 15, teamAbbr: "KC" },
  { id: "kelce", fullName: "Travis Kelce", position: "TE", jersey: 87, teamAbbr: "KC" },
  { id: "pacheco", fullName: "Isiah Pacheco", position: "RB", jersey: 10, teamAbbr: "KC" },
  { id: "rice", fullName: "Rashee Rice", position: "WR", jersey: 4, teamAbbr: "KC" },
  { id: "allen", fullName: "Josh Allen", position: "QB", jersey: 17, teamAbbr: "BUF" },
  { id: "cook", fullName: "James Cook", position: "RB", jersey: 4, teamAbbr: "BUF" },
  { id: "shakir", fullName: "Khalil Shakir", position: "WR", jersey: 10, teamAbbr: "BUF" },
  { id: "purdy", fullName: "Brock Purdy", position: "QB", jersey: 13, teamAbbr: "SF" },
  { id: "cmc", fullName: "Christian McCaffrey", position: "RB", jersey: 23, teamAbbr: "SF" },
  { id: "kittle", fullName: "George Kittle", position: "TE", jersey: 85, teamAbbr: "SF" },
  { id: "geno", fullName: "Geno Smith", position: "QB", jersey: 7, teamAbbr: "SEA" },
  { id: "metcalf", fullName: "DK Metcalf", position: "WR", jersey: 14, teamAbbr: "SEA" },
  { id: "hurts", fullName: "Jalen Hurts", position: "QB", jersey: 1, teamAbbr: "PHI" },
  { id: "saquon", fullName: "Saquon Barkley", position: "RB", jersey: 26, teamAbbr: "PHI" },
  { id: "ajbrown", fullName: "A.J. Brown", position: "WR", jersey: 11, teamAbbr: "PHI" },
  { id: "lamb", fullName: "CeeDee Lamb", position: "WR", jersey: 88, teamAbbr: "DAL" },
  { id: "burrow", fullName: "Joe Burrow", position: "QB", jersey: 9, teamAbbr: "CIN" },
  { id: "chase", fullName: "Ja'Marr Chase", position: "WR", jersey: 1, teamAbbr: "CIN" },
  { id: "lamar", fullName: "Lamar Jackson", position: "QB", jersey: 8, teamAbbr: "BAL" },
  { id: "henry", fullName: "Derrick Henry", position: "RB", jersey: 22, teamAbbr: "BAL" },
  { id: "goff", fullName: "Jared Goff", position: "QB", jersey: 16, teamAbbr: "DET" },
  { id: "gibbs", fullName: "Jahmyr Gibbs", position: "RB", jersey: 26, teamAbbr: "DET" },
  { id: "arsb", fullName: "Amon-Ra St. Brown", position: "WR", jersey: 14, teamAbbr: "DET" },
  { id: "jjefferson", fullName: "Justin Jefferson", position: "WR", jersey: 18, teamAbbr: "MIN" },
];

type RawProp = Omit<PropMarket, "id"> & { id: string };

export const propMarkets: PropMarket[] = (
  [
    {
      id: "mahomes-passyds-buf",
      playerId: "mahomes",
      gameId: "kc-at-buf",
      propType: "PASSING_YARDS",
      line: 274.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "DraftKings",
      projection: 289.4,
      projectionStdDev: 38.2,
      modelHitRateOver: 0.609,
      bookImpliedOver: 0.535,
      edge: 0.074,
      confidence: 0.78,
      recommendation: "OVER",
    },
    {
      id: "mahomes-passatt-buf",
      playerId: "mahomes",
      gameId: "kc-at-buf",
      propType: "PASSING_ATTEMPTS",
      line: 33.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "FanDuel",
      projection: 36.1,
      projectionStdDev: 4.2,
      modelHitRateOver: 0.624,
      bookImpliedOver: 0.524,
      edge: 0.1,
      confidence: 0.82,
      recommendation: "OVER",
    },
    {
      id: "kelce-rec-buf",
      playerId: "kelce",
      gameId: "kc-at-buf",
      propType: "RECEPTIONS",
      line: 6.5,
      overOdds: -135,
      underOdds: +110,
      sportsbook: "DraftKings",
      projection: 6.2,
      projectionStdDev: 1.8,
      modelHitRateOver: 0.482,
      bookImpliedOver: 0.574,
      edge: -0.092,
      confidence: 0.7,
      recommendation: "UNDER",
    },
    {
      id: "kelce-recyds-buf",
      playerId: "kelce",
      gameId: "kc-at-buf",
      propType: "RECEIVING_YARDS",
      line: 64.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "BetMGM",
      projection: 72.3,
      projectionStdDev: 22.4,
      modelHitRateOver: 0.575,
      bookImpliedOver: 0.535,
      edge: 0.04,
      confidence: 0.62,
      recommendation: "OVER",
    },
    {
      id: "pacheco-rushyds-buf",
      playerId: "pacheco",
      gameId: "kc-at-buf",
      propType: "RUSHING_YARDS",
      line: 58.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "Caesars",
      projection: 51.7,
      projectionStdDev: 21.8,
      modelHitRateOver: 0.435,
      bookImpliedOver: 0.524,
      edge: -0.089,
      confidence: 0.66,
      recommendation: "UNDER",
    },
    {
      id: "allen-passyds-kc",
      playerId: "allen",
      gameId: "kc-at-buf",
      propType: "PASSING_YARDS",
      line: 248.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "DraftKings",
      projection: 262.8,
      projectionStdDev: 41.5,
      modelHitRateOver: 0.572,
      bookImpliedOver: 0.524,
      edge: 0.048,
      confidence: 0.6,
      recommendation: "OVER",
    },
    {
      id: "cook-rushatt-kc",
      playerId: "cook",
      gameId: "kc-at-buf",
      propType: "RUSHING_ATTEMPTS",
      line: 14.5,
      overOdds: -120,
      underOdds: +100,
      sportsbook: "FanDuel",
      projection: 16.4,
      projectionStdDev: 3.1,
      modelHitRateOver: 0.621,
      bookImpliedOver: 0.545,
      edge: 0.076,
      confidence: 0.74,
      recommendation: "OVER",
    },
    {
      id: "purdy-passcomp-sea",
      playerId: "purdy",
      gameId: "sf-at-sea",
      propType: "PASSING_COMPLETIONS",
      line: 21.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "DraftKings",
      projection: 23.6,
      projectionStdDev: 3.4,
      modelHitRateOver: 0.612,
      bookImpliedOver: 0.535,
      edge: 0.077,
      confidence: 0.71,
      recommendation: "OVER",
    },
    {
      id: "cmc-rushyds-sea",
      playerId: "cmc",
      gameId: "sf-at-sea",
      propType: "RUSHING_YARDS",
      line: 84.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "BetMGM",
      projection: 96.7,
      projectionStdDev: 28.5,
      modelHitRateOver: 0.602,
      bookImpliedOver: 0.535,
      edge: 0.067,
      confidence: 0.73,
      recommendation: "OVER",
    },
    {
      id: "cmc-rec-sea",
      playerId: "cmc",
      gameId: "sf-at-sea",
      propType: "RECEPTIONS",
      line: 4.5,
      overOdds: -135,
      underOdds: +110,
      sportsbook: "DraftKings",
      projection: 4.3,
      projectionStdDev: 1.6,
      modelHitRateOver: 0.476,
      bookImpliedOver: 0.574,
      edge: -0.098,
      confidence: 0.68,
      recommendation: "UNDER",
    },
    {
      id: "kittle-recyds-sea",
      playerId: "kittle",
      gameId: "sf-at-sea",
      propType: "RECEIVING_YARDS",
      line: 49.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "Caesars",
      projection: 58.4,
      projectionStdDev: 21.8,
      modelHitRateOver: 0.566,
      bookImpliedOver: 0.524,
      edge: 0.042,
      confidence: 0.58,
      recommendation: "OVER",
    },
    {
      id: "metcalf-recyds-sf",
      playerId: "metcalf",
      gameId: "sf-at-sea",
      propType: "RECEIVING_YARDS",
      line: 67.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "FanDuel",
      projection: 62.4,
      projectionStdDev: 27.1,
      modelHitRateOver: 0.471,
      bookImpliedOver: 0.524,
      edge: -0.053,
      confidence: 0.55,
      recommendation: "UNDER",
    },
    {
      id: "hurts-rushatt-dal",
      playerId: "hurts",
      gameId: "phi-at-dal",
      propType: "RUSHING_ATTEMPTS",
      line: 9.5,
      overOdds: -120,
      underOdds: +100,
      sportsbook: "DraftKings",
      projection: 11.2,
      projectionStdDev: 2.5,
      modelHitRateOver: 0.643,
      bookImpliedOver: 0.545,
      edge: 0.098,
      confidence: 0.81,
      recommendation: "OVER",
    },
    {
      id: "saquon-rushyds-dal",
      playerId: "saquon",
      gameId: "phi-at-dal",
      propType: "RUSHING_YARDS",
      line: 92.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "BetMGM",
      projection: 108.3,
      projectionStdDev: 31.2,
      modelHitRateOver: 0.624,
      bookImpliedOver: 0.535,
      edge: 0.089,
      confidence: 0.79,
      recommendation: "OVER",
    },
    {
      id: "ajbrown-rec-dal",
      playerId: "ajbrown",
      gameId: "phi-at-dal",
      propType: "RECEPTIONS",
      line: 5.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "DraftKings",
      projection: 6.4,
      projectionStdDev: 2.0,
      modelHitRateOver: 0.591,
      bookImpliedOver: 0.524,
      edge: 0.067,
      confidence: 0.72,
      recommendation: "OVER",
    },
    {
      id: "lamb-recyds-phi",
      playerId: "lamb",
      gameId: "phi-at-dal",
      propType: "RECEIVING_YARDS",
      line: 87.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "FanDuel",
      projection: 79.6,
      projectionStdDev: 30.4,
      modelHitRateOver: 0.452,
      bookImpliedOver: 0.524,
      edge: -0.072,
      confidence: 0.61,
      recommendation: "UNDER",
    },
    {
      id: "burrow-passyds-bal",
      playerId: "burrow",
      gameId: "cin-at-bal",
      propType: "PASSING_YARDS",
      line: 268.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "DraftKings",
      projection: 284.1,
      projectionStdDev: 39.0,
      modelHitRateOver: 0.591,
      bookImpliedOver: 0.535,
      edge: 0.056,
      confidence: 0.67,
      recommendation: "OVER",
    },
    {
      id: "chase-rec-bal",
      playerId: "chase",
      gameId: "cin-at-bal",
      propType: "RECEPTIONS",
      line: 6.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "BetMGM",
      projection: 7.4,
      projectionStdDev: 2.1,
      modelHitRateOver: 0.585,
      bookImpliedOver: 0.524,
      edge: 0.061,
      confidence: 0.69,
      recommendation: "OVER",
    },
    {
      id: "henry-rushatt-cin",
      playerId: "henry",
      gameId: "cin-at-bal",
      propType: "RUSHING_ATTEMPTS",
      line: 17.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "Caesars",
      projection: 19.6,
      projectionStdDev: 3.4,
      modelHitRateOver: 0.598,
      bookImpliedOver: 0.524,
      edge: 0.074,
      confidence: 0.76,
      recommendation: "OVER",
    },
    {
      id: "henry-rushyds-cin",
      playerId: "henry",
      gameId: "cin-at-bal",
      propType: "RUSHING_YARDS",
      line: 88.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "FanDuel",
      projection: 101.2,
      projectionStdDev: 32.0,
      modelHitRateOver: 0.594,
      bookImpliedOver: 0.535,
      edge: 0.059,
      confidence: 0.7,
      recommendation: "OVER",
    },
    {
      id: "lamar-passyds-cin",
      playerId: "lamar",
      gameId: "cin-at-bal",
      propType: "PASSING_YARDS",
      line: 224.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "DraftKings",
      projection: 218.4,
      projectionStdDev: 42.1,
      modelHitRateOver: 0.458,
      bookImpliedOver: 0.524,
      edge: -0.066,
      confidence: 0.59,
      recommendation: "UNDER",
    },
    {
      id: "goff-passcomp-min",
      playerId: "goff",
      gameId: "det-at-min",
      propType: "PASSING_COMPLETIONS",
      line: 23.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "DraftKings",
      projection: 25.8,
      projectionStdDev: 3.2,
      modelHitRateOver: 0.612,
      bookImpliedOver: 0.535,
      edge: 0.077,
      confidence: 0.74,
      recommendation: "OVER",
    },
    {
      id: "gibbs-rushyds-min",
      playerId: "gibbs",
      gameId: "det-at-min",
      propType: "RUSHING_YARDS",
      line: 64.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "BetMGM",
      projection: 73.6,
      projectionStdDev: 25.4,
      modelHitRateOver: 0.575,
      bookImpliedOver: 0.524,
      edge: 0.051,
      confidence: 0.65,
      recommendation: "OVER",
    },
    {
      id: "arsb-recyds-min",
      playerId: "arsb",
      gameId: "det-at-min",
      propType: "RECEIVING_YARDS",
      line: 78.5,
      overOdds: -110,
      underOdds: -110,
      sportsbook: "DraftKings",
      projection: 86.8,
      projectionStdDev: 27.3,
      modelHitRateOver: 0.572,
      bookImpliedOver: 0.524,
      edge: 0.048,
      confidence: 0.63,
      recommendation: "OVER",
    },
    {
      id: "jjefferson-recyds-det",
      playerId: "jjefferson",
      gameId: "det-at-min",
      propType: "RECEIVING_YARDS",
      line: 89.5,
      overOdds: -115,
      underOdds: -105,
      sportsbook: "FanDuel",
      projection: 98.4,
      projectionStdDev: 31.2,
      modelHitRateOver: 0.566,
      bookImpliedOver: 0.535,
      edge: 0.031,
      confidence: 0.6,
      recommendation: "PASS",
    },
  ] satisfies RawProp[]
).map((p) => p as PropMarket);

const recentLogsByPlayer: Record<string, GameLog[]> = {
  mahomes: [
    { season: 2025, week: 10, opponentAbbr: "DEN", passingAttempts: 38, passingCompletions: 27, passingYards: 312, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 14 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 35, passingCompletions: 24, passingYards: 268, receptions: 0, receivingYards: 0, rushingAttempts: 4, rushingYards: 22 },
    { season: 2025, week: 8, opponentAbbr: "LV", passingAttempts: 41, passingCompletions: 30, passingYards: 294, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 6 },
    { season: 2025, week: 7, opponentAbbr: "SF", passingAttempts: 39, passingCompletions: 28, passingYards: 343, receptions: 0, receivingYards: 0, rushingAttempts: 4, rushingYards: 18 },
    { season: 2025, week: 6, opponentAbbr: "NO", passingAttempts: 33, passingCompletions: 22, passingYards: 245, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 11 },
  ],
  kelce: [
    { season: 2025, week: 10, opponentAbbr: "DEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 78, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 52, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "LV", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 94, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "SF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 48, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "NO", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 73, rushingAttempts: 0, rushingYards: 0 },
  ],
  pacheco: [
    { season: 2025, week: 10, opponentAbbr: "DEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 12, rushingAttempts: 14, rushingYards: 48 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 19, rushingAttempts: 11, rushingYards: 36 },
    { season: 2025, week: 8, opponentAbbr: "LV", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 1, receivingYards: 6, rushingAttempts: 16, rushingYards: 64 },
    { season: 2025, week: 7, opponentAbbr: "SF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 10, rushingAttempts: 12, rushingYards: 41 },
    { season: 2025, week: 6, opponentAbbr: "NO", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 22, rushingAttempts: 18, rushingYards: 72 },
  ],
  allen: [
    { season: 2025, week: 10, opponentAbbr: "IND", passingAttempts: 31, passingCompletions: 22, passingYards: 284, receptions: 0, receivingYards: 0, rushingAttempts: 8, rushingYards: 41 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 28, passingCompletions: 18, passingYards: 224, receptions: 0, receivingYards: 0, rushingAttempts: 7, rushingYards: 38 },
    { season: 2025, week: 8, opponentAbbr: "SEA", passingAttempts: 33, passingCompletions: 24, passingYards: 296, receptions: 0, receivingYards: 0, rushingAttempts: 6, rushingYards: 22 },
    { season: 2025, week: 7, opponentAbbr: "TEN", passingAttempts: 27, passingCompletions: 17, passingYards: 244, receptions: 0, receivingYards: 0, rushingAttempts: 9, rushingYards: 54 },
    { season: 2025, week: 6, opponentAbbr: "NYJ", passingAttempts: 35, passingCompletions: 23, passingYards: 271, receptions: 0, receivingYards: 0, rushingAttempts: 5, rushingYards: 26 },
  ],
  cook: [
    { season: 2025, week: 10, opponentAbbr: "IND", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 22, rushingAttempts: 17, rushingYards: 86 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 14, rushingAttempts: 14, rushingYards: 62 },
    { season: 2025, week: 8, opponentAbbr: "SEA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 28, rushingAttempts: 19, rushingYards: 98 },
    { season: 2025, week: 7, opponentAbbr: "TEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 1, receivingYards: 8, rushingAttempts: 16, rushingYards: 71 },
    { season: 2025, week: 6, opponentAbbr: "NYJ", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 18, rushingAttempts: 15, rushingYards: 64 },
  ],
  purdy: [
    { season: 2025, week: 10, opponentAbbr: "TB", passingAttempts: 32, passingCompletions: 22, passingYards: 271, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 12 },
    { season: 2025, week: 9, opponentAbbr: "DAL", passingAttempts: 35, passingCompletions: 24, passingYards: 298, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 8 },
    { season: 2025, week: 8, opponentAbbr: "ARI", passingAttempts: 30, passingCompletions: 21, passingYards: 248, receptions: 0, receivingYards: 0, rushingAttempts: 4, rushingYards: 16 },
    { season: 2025, week: 7, opponentAbbr: "KC", passingAttempts: 34, passingCompletions: 25, passingYards: 283, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 14 },
    { season: 2025, week: 6, opponentAbbr: "SEA", passingAttempts: 28, passingCompletions: 20, passingYards: 234, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 9 },
  ],
  cmc: [
    { season: 2025, week: 10, opponentAbbr: "TB", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 32, rushingAttempts: 22, rushingYards: 108 },
    { season: 2025, week: 9, opponentAbbr: "DAL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 42, rushingAttempts: 20, rushingYards: 94 },
    { season: 2025, week: 8, opponentAbbr: "ARI", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 24, rushingAttempts: 24, rushingYards: 121 },
    { season: 2025, week: 7, opponentAbbr: "KC", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 48, rushingAttempts: 18, rushingYards: 76 },
    { season: 2025, week: 6, opponentAbbr: "SEA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 36, rushingAttempts: 21, rushingYards: 88 },
  ],
  kittle: [
    { season: 2025, week: 10, opponentAbbr: "TB", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 64, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "DAL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 52, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "ARI", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 78, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "KC", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 38, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "SEA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 71, rushingAttempts: 0, rushingYards: 0 },
  ],
  metcalf: [
    { season: 2025, week: 10, opponentAbbr: "LAR", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 58, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "BUF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 72, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "ARI", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 41, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "ATL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 96, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "SF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 51, rushingAttempts: 0, rushingYards: 0 },
  ],
  hurts: [
    { season: 2025, week: 10, opponentAbbr: "WAS", passingAttempts: 28, passingCompletions: 19, passingYards: 224, receptions: 0, receivingYards: 0, rushingAttempts: 11, rushingYards: 56 },
    { season: 2025, week: 9, opponentAbbr: "JAX", passingAttempts: 30, passingCompletions: 21, passingYards: 248, receptions: 0, receivingYards: 0, rushingAttempts: 10, rushingYards: 48 },
    { season: 2025, week: 8, opponentAbbr: "CIN", passingAttempts: 32, passingCompletions: 22, passingYards: 271, receptions: 0, receivingYards: 0, rushingAttempts: 12, rushingYards: 62 },
    { season: 2025, week: 7, opponentAbbr: "NYG", passingAttempts: 26, passingCompletions: 17, passingYards: 198, receptions: 0, receivingYards: 0, rushingAttempts: 13, rushingYards: 71 },
    { season: 2025, week: 6, opponentAbbr: "CLE", passingAttempts: 31, passingCompletions: 21, passingYards: 256, receptions: 0, receivingYards: 0, rushingAttempts: 9, rushingYards: 41 },
  ],
  saquon: [
    { season: 2025, week: 10, opponentAbbr: "WAS", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 24, rushingAttempts: 21, rushingYards: 112 },
    { season: 2025, week: 9, opponentAbbr: "JAX", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 18, rushingAttempts: 24, rushingYards: 138 },
    { season: 2025, week: 8, opponentAbbr: "CIN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 32, rushingAttempts: 19, rushingYards: 88 },
    { season: 2025, week: 7, opponentAbbr: "NYG", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 26, rushingAttempts: 23, rushingYards: 124 },
    { season: 2025, week: 6, opponentAbbr: "CLE", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 16, rushingAttempts: 18, rushingYards: 76 },
  ],
  ajbrown: [
    { season: 2025, week: 10, opponentAbbr: "WAS", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 96, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "JAX", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 72, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "CIN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 124, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "NYG", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 58, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "CLE", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 88, rushingAttempts: 0, rushingYards: 0 },
  ],
  lamb: [
    { season: 2025, week: 10, opponentAbbr: "ATL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 74, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "SF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 82, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "DET", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 96, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "PIT", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 52, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "BAL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 88, rushingAttempts: 0, rushingYards: 0 },
  ],
  burrow: [
    { season: 2025, week: 10, opponentAbbr: "LV", passingAttempts: 38, passingCompletions: 28, passingYards: 312, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 4 },
    { season: 2025, week: 9, opponentAbbr: "PHI", passingAttempts: 41, passingCompletions: 27, passingYards: 286, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 8 },
    { season: 2025, week: 8, opponentAbbr: "CLE", passingAttempts: 36, passingCompletions: 24, passingYards: 261, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 2 },
    { season: 2025, week: 7, opponentAbbr: "PIT", passingAttempts: 39, passingCompletions: 26, passingYards: 288, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 6 },
    { season: 2025, week: 6, opponentAbbr: "NYG", passingAttempts: 35, passingCompletions: 25, passingYards: 274, receptions: 0, receivingYards: 0, rushingAttempts: 3, rushingYards: 12 },
  ],
  chase: [
    { season: 2025, week: 10, opponentAbbr: "LV", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 112, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "PHI", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 88, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "CLE", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 94, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "PIT", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 9, receivingYards: 128, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "NYG", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 71, rushingAttempts: 0, rushingYards: 0 },
  ],
  lamar: [
    { season: 2025, week: 10, opponentAbbr: "PIT", passingAttempts: 26, passingCompletions: 17, passingYards: 218, receptions: 0, receivingYards: 0, rushingAttempts: 8, rushingYards: 62 },
    { season: 2025, week: 9, opponentAbbr: "DEN", passingAttempts: 28, passingCompletions: 19, passingYards: 244, receptions: 0, receivingYards: 0, rushingAttempts: 11, rushingYards: 78 },
    { season: 2025, week: 8, opponentAbbr: "CLE", passingAttempts: 24, passingCompletions: 16, passingYards: 198, receptions: 0, receivingYards: 0, rushingAttempts: 9, rushingYards: 54 },
    { season: 2025, week: 7, opponentAbbr: "TB", passingAttempts: 30, passingCompletions: 21, passingYards: 268, receptions: 0, receivingYards: 0, rushingAttempts: 7, rushingYards: 48 },
    { season: 2025, week: 6, opponentAbbr: "WAS", passingAttempts: 27, passingCompletions: 18, passingYards: 226, receptions: 0, receivingYards: 0, rushingAttempts: 10, rushingYards: 72 },
  ],
  henry: [
    { season: 2025, week: 10, opponentAbbr: "PIT", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 1, receivingYards: 8, rushingAttempts: 18, rushingYards: 92 },
    { season: 2025, week: 9, opponentAbbr: "DEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 14, rushingAttempts: 22, rushingYards: 124 },
    { season: 2025, week: 8, opponentAbbr: "CLE", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 1, receivingYards: 6, rushingAttempts: 17, rushingYards: 78 },
    { season: 2025, week: 7, opponentAbbr: "TB", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 12, rushingAttempts: 20, rushingYards: 108 },
    { season: 2025, week: 6, opponentAbbr: "WAS", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 1, receivingYards: 4, rushingAttempts: 19, rushingYards: 88 },
  ],
  goff: [
    { season: 2025, week: 10, opponentAbbr: "HOU", passingAttempts: 34, passingCompletions: 25, passingYards: 274, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 2 },
    { season: 2025, week: 9, opponentAbbr: "GB", passingAttempts: 36, passingCompletions: 27, passingYards: 298, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 4 },
    { season: 2025, week: 8, opponentAbbr: "TEN", passingAttempts: 32, passingCompletions: 24, passingYards: 256, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 1 },
    { season: 2025, week: 7, opponentAbbr: "MIN", passingAttempts: 38, passingCompletions: 26, passingYards: 312, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 6 },
    { season: 2025, week: 6, opponentAbbr: "DAL", passingAttempts: 30, passingCompletions: 22, passingYards: 248, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 3 },
  ],
  gibbs: [
    { season: 2025, week: 10, opponentAbbr: "HOU", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 28, rushingAttempts: 16, rushingYards: 78 },
    { season: 2025, week: 9, opponentAbbr: "GB", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 22, rushingAttempts: 18, rushingYards: 94 },
    { season: 2025, week: 8, opponentAbbr: "TEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 36, rushingAttempts: 14, rushingYards: 62 },
    { season: 2025, week: 7, opponentAbbr: "MIN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 2, receivingYards: 18, rushingAttempts: 17, rushingYards: 88 },
    { season: 2025, week: 6, opponentAbbr: "DAL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 32, rushingAttempts: 15, rushingYards: 71 },
  ],
  arsb: [
    { season: 2025, week: 10, opponentAbbr: "HOU", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 92, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "GB", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 9, receivingYards: 108, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "TEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 78, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "MIN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 64, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "DAL", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 96, rushingAttempts: 0, rushingYards: 0 },
  ],
  jjefferson: [
    { season: 2025, week: 10, opponentAbbr: "JAX", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 104, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "IND", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 92, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "LAR", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 8, receivingYards: 121, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "DET", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 78, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "NYJ", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 96, rushingAttempts: 0, rushingYards: 0 },
  ],
  rice: [
    { season: 2025, week: 10, opponentAbbr: "DEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 64, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 52, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "LV", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 78, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "SF", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 36, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "NO", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 7, receivingYards: 88, rushingAttempts: 0, rushingYards: 0 },
  ],
  shakir: [
    { season: 2025, week: 10, opponentAbbr: "IND", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 48, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 9, opponentAbbr: "MIA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 3, receivingYards: 36, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 8, opponentAbbr: "SEA", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 5, receivingYards: 62, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 7, opponentAbbr: "TEN", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 4, receivingYards: 54, rushingAttempts: 0, rushingYards: 0 },
    { season: 2025, week: 6, opponentAbbr: "NYJ", passingAttempts: 0, passingCompletions: 0, passingYards: 0, receptions: 6, receivingYards: 71, rushingAttempts: 0, rushingYards: 0 },
  ],
  geno: [
    { season: 2025, week: 10, opponentAbbr: "LAR", passingAttempts: 30, passingCompletions: 21, passingYards: 248, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 6 },
    { season: 2025, week: 9, opponentAbbr: "BUF", passingAttempts: 34, passingCompletions: 23, passingYards: 286, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 4 },
    { season: 2025, week: 8, opponentAbbr: "ARI", passingAttempts: 28, passingCompletions: 19, passingYards: 224, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 8 },
    { season: 2025, week: 7, opponentAbbr: "ATL", passingAttempts: 32, passingCompletions: 22, passingYards: 262, receptions: 0, receivingYards: 0, rushingAttempts: 1, rushingYards: 2 },
    { season: 2025, week: 6, opponentAbbr: "SF", passingAttempts: 29, passingCompletions: 20, passingYards: 234, receptions: 0, receivingYards: 0, rushingAttempts: 2, rushingYards: 5 },
  ],
};

const altLinesByProp: Record<string, LineQuote[]> = {
  "mahomes-passyds-buf": [
    { sportsbook: "DraftKings", line: 274.5, overOdds: -115, underOdds: -105 },
    { sportsbook: "FanDuel", line: 273.5, overOdds: -118, underOdds: -102 },
    { sportsbook: "BetMGM", line: 275.5, overOdds: -110, underOdds: -110 },
    { sportsbook: "Caesars", line: 274.5, overOdds: -112, underOdds: -108 },
  ],
  "mahomes-passatt-buf": [
    { sportsbook: "FanDuel", line: 33.5, overOdds: -110, underOdds: -110 },
    { sportsbook: "DraftKings", line: 33.5, overOdds: -115, underOdds: -105 },
    { sportsbook: "BetMGM", line: 34.5, overOdds: +110, underOdds: -130 },
  ],
};

const defaultAltLines = (base: PropMarket): LineQuote[] => [
  { sportsbook: base.sportsbook, line: base.line, overOdds: base.overOdds, underOdds: base.underOdds },
  { sportsbook: alternateBook(base.sportsbook, 0), line: base.line, overOdds: base.overOdds + 5, underOdds: base.underOdds - 5 },
  { sportsbook: alternateBook(base.sportsbook, 1), line: base.line + 0.5, overOdds: base.overOdds + 10, underOdds: base.underOdds - 15 },
  { sportsbook: alternateBook(base.sportsbook, 2), line: base.line - 0.5, overOdds: base.overOdds - 10, underOdds: base.underOdds + 5 },
];

function alternateBook(current: string, offset: number): string {
  const all = ["DraftKings", "FanDuel", "BetMGM", "Caesars", "ESPN BET"];
  const filtered = all.filter((b) => b !== current);
  return filtered[offset % filtered.length];
}

const matchupNotesByProp: Record<string, string[]> = {
  "mahomes-passyds-buf": [
    "Bills defense allowing 7.4 yards per attempt to QBs over last 4 weeks (28th).",
    "KC pass rate over expectation is +5.2% in road games this season.",
    "Game total of 48.5 is third-highest on the slate; pace neutral environment.",
  ],
  "mahomes-passatt-buf": [
    "Pacheco questionable — backfield committee likely pushes ATTs higher.",
    "Buffalo run defense ranks 6th in DVOA, encourages dropbacks.",
    "Mahomes averaging 36.8 attempts vs winning records this year.",
  ],
  "kelce-rec-buf": [
    "Bills allow only 5.3 rec/game to TEs since Week 6 — top-10 mark.",
    "Kelce's target share trending down (24% → 19% L4).",
    "Worthy/Rice ascending in route hierarchy.",
  ],
  "saquon-rushyds-dal": [
    "Dallas run defense allowing 5.1 YPC over last 5 weeks (30th).",
    "Eagles RB usage in neutral game scripts: 24.6 carries/game.",
    "Saquon over rushing yards line in 7 of 9 games this season.",
  ],
};

export function getProps(): PropMarket[] {
  return propMarkets;
}

export function getRecentLogsFromMock(playerId: string): GameLog[] {
  return recentLogsByPlayer[playerId] ?? [];
}

export const backtestMockSummary: BacktestSummary = {
  windowLabel: "Weeks 1–10, 2025 season",
  totalPlays: 247,
  wins: 132,
  losses: 107,
  pushes: 8,
  unitsStaked: 247,
  unitsReturn: 265.4,
  roiPct: 7.5,
  byMarket: [
    { propType: "PASSING_YARDS", plays: 38, hitRate: 0.605, roiUnits: 4.2, roiPct: 11.1 },
    { propType: "PASSING_ATTEMPTS", plays: 24, hitRate: 0.583, roiUnits: 2.1, roiPct: 8.8 },
    { propType: "PASSING_COMPLETIONS", plays: 22, hitRate: 0.591, roiUnits: 1.6, roiPct: 7.3 },
    { propType: "RECEPTIONS", plays: 41, hitRate: 0.488, roiUnits: -0.9, roiPct: -2.2 },
    { propType: "RECEIVING_YARDS", plays: 45, hitRate: 0.578, roiUnits: 3.4, roiPct: 7.6 },
    { propType: "RUSHING_ATTEMPTS", plays: 33, hitRate: 0.545, roiUnits: 1.1, roiPct: 3.3 },
    { propType: "RUSHING_YARDS", plays: 44, hitRate: 0.591, roiUnits: 6.9, roiPct: 15.7 },
  ],
  bestMarket: { propType: "RUSHING_YARDS", plays: 44, hitRate: 0.591, roiUnits: 6.9, roiPct: 15.7 },
  worstMarket: { propType: "RECEPTIONS", plays: 41, hitRate: 0.488, roiUnits: -0.9, roiPct: -2.2 },
};

export function getPropById(id: string): PropMarket | undefined {
  return propMarkets.find((p) => p.id === id);
}

export function getPlayerById(id: string): Player | undefined {
  return players.find((p) => p.id === id);
}

export function getTeam(abbr: string): Team | undefined {
  return teams[abbr];
}

export function getGameById(id: string): Game | undefined {
  return games.find((g) => g.id === id);
}

export function getPropDetail(id: string): PropDetail | undefined {
  const prop = getPropById(id);
  if (!prop) return undefined;
  const player = getPlayerById(prop.playerId);
  if (!player) return undefined;
  const team = getTeam(player.teamAbbr);
  if (!team) return undefined;
  const game = getGameById(prop.gameId);
  if (!game) return undefined;
  const opponentAbbr =
    game.homeTeamAbbr === player.teamAbbr ? game.awayTeamAbbr : game.homeTeamAbbr;
  const opponent = getTeam(opponentAbbr);
  if (!opponent) return undefined;
  return {
    ...prop,
    player,
    team,
    opponent,
    game,
    recentLogs: recentLogsByPlayer[player.id] ?? [],
    altLines: altLinesByProp[prop.id] ?? defaultAltLines(prop),
    matchupNotes: matchupNotesByProp[prop.id] ?? defaultMatchupNotes(prop, player.fullName, opponent.abbreviation),
  };
}

function defaultMatchupNotes(prop: PropMarket, playerName: string, opponent: string): string[] {
  return [
    `${playerName}'s recent usage trending in line with projected role vs ${opponent}.`,
    `Model projection sits ${(((prop.projection - prop.line) / prop.line) * 100).toFixed(1)}% off market line.`,
    `Edge held since latest line refresh — confidence rated ${prop.confidence >= 0.7 ? "high" : prop.confidence >= 0.6 ? "medium" : "low"}.`,
  ];
}
