import type { PropType } from "../types";
import type {
  BlendProfileKey,
  BlendWeights,
  CoachTendencyProfile,
  SeasonPhase,
  TeamCoachingTransition,
} from "./coaching-transition-types";

export const BLEND_PROFILES: Record<
  BlendProfileKey,
  Record<SeasonPhase, BlendWeights>
> = {
  high_continuity: {
    WEEKS_1_4: { priorTeam: 70, coachProfile: 20, leagueAverage: 10, currentSeasonObserved: 0 },
    WEEKS_5_8: { priorTeam: 45, coachProfile: 20, leagueAverage: 10, currentSeasonObserved: 25 },
    WEEKS_9_PLUS: { priorTeam: 20, coachProfile: 10, leagueAverage: 10, currentSeasonObserved: 60 },
  },
  new_oc_same_hc: {
    WEEKS_1_4: { priorTeam: 40, coachProfile: 40, leagueAverage: 20, currentSeasonObserved: 0 },
    WEEKS_5_8: { priorTeam: 25, coachProfile: 25, leagueAverage: 15, currentSeasonObserved: 35 },
    WEEKS_9_PLUS: { priorTeam: 10, coachProfile: 15, leagueAverage: 10, currentSeasonObserved: 65 },
  },
  new_hc_new_oc: {
    WEEKS_1_4: { priorTeam: 25, coachProfile: 45, leagueAverage: 30, currentSeasonObserved: 0 },
    WEEKS_5_8: { priorTeam: 15, coachProfile: 25, leagueAverage: 15, currentSeasonObserved: 45 },
    WEEKS_9_PLUS: { priorTeam: 5, coachProfile: 10, leagueAverage: 10, currentSeasonObserved: 75 },
  },
  new_hc_new_oc_unstable_qb: {
    WEEKS_1_4: { priorTeam: 15, coachProfile: 35, leagueAverage: 50, currentSeasonObserved: 0 },
    WEEKS_5_8: { priorTeam: 10, coachProfile: 20, leagueAverage: 20, currentSeasonObserved: 50 },
    WEEKS_9_PLUS: { priorTeam: 5, coachProfile: 5, leagueAverage: 10, currentSeasonObserved: 80 },
  },
};

export const COACH_TENDENCY_PROFILES: Record<string, CoachTendencyProfile> = {
  LEAGUE_AVERAGE_2025: {
    key: "LEAGUE_AVERAGE_2025",
    description: "League average baseline for the 2025 season",
    signatureNotes: [
      "~59% pass / 41% run on early downs",
      "~27% play-action rate",
      "~63 plays per game",
    ],
  },
  WEST_COAST_PLAY_ACTION: {
    key: "WEST_COAST_PLAY_ACTION",
    description: "Shanahan / McVay tree: outside zone, play-action heavy, YAC-driven",
    signatureNotes: [
      "Above-average run rate on early downs",
      "Heavy play-action and bootleg integration",
      "Targets short / intermediate areas with YAC focus",
    ],
  },
  AIR_RAID_VERTICAL: {
    key: "AIR_RAID_VERTICAL",
    description: "Vertical pass concepts, high deep rate, lower run rate",
    signatureNotes: [
      "Above-average pass rate",
      "Higher deep-shot frequency",
      "Tighter early-down splits, more shotgun",
    ],
  },
  HEAVY_PERSONNEL_RUN_FIRST: {
    key: "HEAVY_PERSONNEL_RUN_FIRST",
    description: "Under-center, 12-personnel, lead / zone runs, TE-focused passing",
    signatureNotes: [
      "Below-average pass rate",
      "12-personnel above league average",
      "Higher TE target share",
    ],
  },
};

const NEUTRAL_IMPACTS: Record<PropType, string> = {
  PASSING_ATTEMPTS: "neutral",
  PASSING_COMPLETIONS: "neutral",
  PASSING_YARDS: "neutral",
  RECEPTIONS: "neutral",
  RECEIVING_YARDS: "neutral",
  RUSHING_ATTEMPTS: "neutral",
  RUSHING_YARDS: "neutral",
};

export const UNCHANGED_STAFF_DEFAULT: TeamCoachingTransition = {
  team: "DEFAULT",
  season: 2026,
  blendProfile: "high_continuity",
  scores: {
    coachingContinuityScore: 88,
    offensivePlayCallerChangeScore: 0,
    defensivePlayCallerChangeScore: 0,
    teamTendencyTrustScore: 82,
    offensiveIdentityShiftScore: 8,
    defensiveIdentityShiftScore: 8,
    playCallerConfidenceScore: 95,
    coachingUncertaintyPenalty: 8,
  },
  notes: [
    "Default profile for teams without explicitly encoded 2026 staff transition signal.",
  ],
  offenseDeltas: [],
  defenseDeltas: [],
  propImpacts: { ...NEUTRAL_IMPACTS },
  sourceConfidence: "MEDIUM",
  assumptionNotes: [
    "Default profile for teams without explicitly encoded 2026 staff transition signal.",
  ],
  lastVerified: "2026-05-19",
  appliesToWeeks: "Weeks 1-8 unless observed 2026 data becomes available",
};

export const TEAM_COACHING_TRANSITIONS: Record<string, TeamCoachingTransition> = {
  BUF: {
    team: "BUF",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 80,
      offensivePlayCallerChangeScore: 15,
      defensivePlayCallerChangeScore: 70,
      teamTendencyTrustScore: 72,
      offensiveIdentityShiftScore: 20,
      defensiveIdentityShiftScore: 55,
      playCallerConfidenceScore: 90,
      coachingUncertaintyPenalty: 18,
    },
    notes: [
      "Promoted HC but same offensive brain; offense mostly stable.",
    ],
    offenseDeltas: [],
    defenseDeltas: [],
    propImpacts: { ...NEUTRAL_IMPACTS },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Treat offense as mostly stable; defensive/staff title changes should not materially change offensive prop priors.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8, then let observed 2026 data dominate",
  },
  ARI: {
    team: "ARI",
    season: 2026,
    blendProfile: "new_hc_new_oc",
    scores: {
      coachingContinuityScore: 25,
      offensivePlayCallerChangeScore: 95,
      defensivePlayCallerChangeScore: 20,
      teamTendencyTrustScore: 35,
      offensiveIdentityShiftScore: 85,
      defensiveIdentityShiftScore: 35,
      playCallerConfidenceScore: 90,
      coachingUncertaintyPenalty: 55,
    },
    notes: ["New offensive identity; prior tendencies have low trust early."],
    offenseDeltas: [
      "UNDER_CENTER_UP",
      "PLAY_ACTION_UP",
      "PACE_DOWN",
      "PASS_RATE_DOWN",
      "TWELVE_PERSONNEL_UP",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "down",
      PASSING_COMPLETIONS: "uncertain",
      PASSING_YARDS: "down",
      RECEPTIONS: "down",
      RECEIVING_YARDS: "down",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "New offensive identity should reduce trust in prior-year tendencies; early-season props require larger edge.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  LV: {
    team: "LV",
    season: 2026,
    blendProfile: "new_hc_new_oc",
    scores: {
      coachingContinuityScore: 20,
      offensivePlayCallerChangeScore: 95,
      defensivePlayCallerChangeScore: 35,
      teamTendencyTrustScore: 30,
      offensiveIdentityShiftScore: 85,
      defensiveIdentityShiftScore: 25,
      playCallerConfidenceScore: 90,
      coachingUncertaintyPenalty: 60,
    },
    notes: ["Major offensive reset."],
    offenseDeltas: [
      "PLAY_ACTION_UP",
      "EFFICIENCY_UP",
      "TE_USAGE_UP",
      "RUN_COMMITMENT_UP",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "uncertain",
      PASSING_COMPLETIONS: "up",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "up for TE/short-area roles",
      RECEIVING_YARDS: "up for efficiency players",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Major offensive reset; coach context should increase uncertainty and require stronger edge.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  CLE: {
    team: "CLE",
    season: 2026,
    blendProfile: "new_hc_new_oc",
    scores: {
      coachingContinuityScore: 28,
      offensivePlayCallerChangeScore: 95,
      defensivePlayCallerChangeScore: 60,
      teamTendencyTrustScore: 32,
      offensiveIdentityShiftScore: 88,
      defensiveIdentityShiftScore: 35,
      playCallerConfidenceScore: 88,
      coachingUncertaintyPenalty: 58,
    },
    notes: [
      "Explosive passing / rushing structure may improve yards but increase volatility.",
    ],
    offenseDeltas: ["RUN_ACTION_UP", "AIR_YARDS_UP", "EXPLOSIVE_PASS_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "uncertain",
      PASSING_YARDS: "up",
      RECEPTIONS: "uncertain",
      RECEIVING_YARDS: "up",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Explosive passing/rushing structure may improve yards but increase volatility; do not blindly upgrade completions.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  TEN: {
    team: "TEN",
    season: 2026,
    blendProfile: "new_hc_new_oc_unstable_qb",
    scores: {
      coachingContinuityScore: 22,
      offensivePlayCallerChangeScore: 92,
      defensivePlayCallerChangeScore: 90,
      teamTendencyTrustScore: 28,
      offensiveIdentityShiftScore: 75,
      defensiveIdentityShiftScore: 80,
      playCallerConfidenceScore: 92,
      coachingUncertaintyPenalty: 65,
    },
    notes: ["Full reset; prior-team tendencies have low trust early."],
    offenseDeltas: ["DEEP_RATE_UP", "AIR_YARDS_UP", "TRAILING_PASS_UP"],
    defenseDeltas: ["FRONT_43_UP", "ZONE_UP", "BLITZ_DOWN"],
    propImpacts: {
      PASSING_ATTEMPTS: "up",
      PASSING_COMPLETIONS: "uncertain",
      PASSING_YARDS: "up",
      RECEPTIONS: "uncertain",
      RECEIVING_YARDS: "up",
      RUSHING_ATTEMPTS: "neutral",
      RUSHING_YARDS: "neutral",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Full reset; prior-team tendencies have low trust early. Increase uncertainty penalty.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  NYG: {
    team: "NYG",
    season: 2026,
    blendProfile: "new_hc_new_oc_unstable_qb",
    scores: {
      coachingContinuityScore: 18,
      offensivePlayCallerChangeScore: 88,
      defensivePlayCallerChangeScore: 82,
      teamTendencyTrustScore: 25,
      offensiveIdentityShiftScore: 78,
      defensiveIdentityShiftScore: 55,
      playCallerConfidenceScore: 90,
      coachingUncertaintyPenalty: 70,
    },
    notes: ["High early uncertainty."],
    offenseDeltas: [
      "ELEVEN_PERSONNEL_DOWN",
      "TWELVE_PERSONNEL_UP",
      "PACE_DOWN",
      "LEAD_RUN_UP",
      "TE_USAGE_UP",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "down",
      PASSING_COMPLETIONS: "down/uncertain",
      PASSING_YARDS: "down",
      RECEPTIONS: "down except TE",
      RECEIVING_YARDS: "down except TE",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "High early uncertainty; marginal edges should be passed until observed 2026 usage is available.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  MIA: {
    team: "MIA",
    season: 2026,
    blendProfile: "new_hc_new_oc",
    scores: {
      coachingContinuityScore: 15,
      offensivePlayCallerChangeScore: 78,
      defensivePlayCallerChangeScore: 92,
      teamTendencyTrustScore: 20,
      offensiveIdentityShiftScore: 82,
      defensiveIdentityShiftScore: 85,
      playCallerConfidenceScore: 85,
      coachingUncertaintyPenalty: 75,
    },
    notes: ["High identity uncertainty across both sides of the ball."],
    offenseDeltas: [
      "UNDER_CENTER_UP",
      "PLAY_ACTION_UP",
      "PACE_DOWN",
      "PASS_RATE_DOWN",
      "YAC_UP",
    ],
    defenseDeltas: ["BLITZ_DOWN", "ZONE_UP", "MAN_DOWN", "TWO_HIGH_UP"],
    propImpacts: {
      PASSING_ATTEMPTS: "down",
      PASSING_COMPLETIONS: "uncertain",
      PASSING_YARDS: "down/uncertain",
      RECEPTIONS: "down/uncertain",
      RECEIVING_YARDS: "down/uncertain",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "High identity uncertainty; coaching layer should mainly raise thresholds early.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  BAL: {
    team: "BAL",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 30,
      offensivePlayCallerChangeScore: 80,
      defensivePlayCallerChangeScore: 88,
      teamTendencyTrustScore: 33,
      offensiveIdentityShiftScore: 60,
      defensiveIdentityShiftScore: 72,
      playCallerConfidenceScore: 92,
      coachingUncertaintyPenalty: 55,
    },
    notes: ["Rushing confidence can improve more than raw rushing volume."],
    offenseDeltas: [
      "BALANCE_UP",
      "RUN_STRUCTURE_UP",
      "PASS_GAME_MORE_UNCERTAIN",
    ],
    defenseDeltas: ["BLITZ_DOWN", "ZONE_UP", "SPLIT_SAFETY_UP"],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "neutral",
      PASSING_YARDS: "neutral/uncertain",
      RECEPTIONS: "neutral",
      RECEIVING_YARDS: "neutral",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Rushing confidence can improve more than raw rushing volume."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  PIT: {
    team: "PIT",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 18,
      offensivePlayCallerChangeScore: 90,
      defensivePlayCallerChangeScore: 75,
      teamTendencyTrustScore: 25,
      offensiveIdentityShiftScore: 72,
      defensiveIdentityShiftScore: 50,
      playCallerConfidenceScore: 95,
      coachingUncertaintyPenalty: 65,
    },
    notes: [
      "Major offensive identity shift; increase uncertainty and rely less on prior team run/pass split.",
    ],
    offenseDeltas: [
      "SHOTGUN_UP",
      "WIDE_FORMATIONS_UP",
      "MULTIPLE_TE_DOWN",
      "PASS_VOLUME_UP",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "up",
      PASSING_COMPLETIONS: "up/uncertain",
      PASSING_YARDS: "up",
      RECEPTIONS: "up for WRs",
      RECEIVING_YARDS: "up",
      RUSHING_ATTEMPTS: "down",
      RUSHING_YARDS: "down/neutral",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Major offensive identity shift; increase uncertainty and rely less on prior team run/pass split.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  ATL: {
    team: "ATL",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 40,
      offensivePlayCallerChangeScore: 82,
      defensivePlayCallerChangeScore: 15,
      teamTendencyTrustScore: 42,
      offensiveIdentityShiftScore: 76,
      defensiveIdentityShiftScore: 20,
      playCallerConfidenceScore: 88,
      coachingUncertaintyPenalty: 48,
    },
    notes: [
      "Run structure improvement should affect rushing efficiency more than automatic rushing volume.",
    ],
    offenseDeltas: ["UNDER_CENTER_UP", "PLAY_ACTION_UP", "RUN_STRUCTURE_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "neutral/up",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "neutral",
      RECEIVING_YARDS: "neutral",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Run structure improvement should affect rushing efficiency more than automatic rushing volume.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  LAC: {
    team: "LAC",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 65,
      offensivePlayCallerChangeScore: 78,
      defensivePlayCallerChangeScore: 0,
      teamTendencyTrustScore: 55,
      offensiveIdentityShiftScore: 52,
      defensiveIdentityShiftScore: 5,
      playCallerConfidenceScore: 90,
      coachingUncertaintyPenalty: 32,
    },
    notes: [
      "Same larger team identity but new offensive tendencies; moderate uncertainty.",
    ],
    offenseDeltas: ["MOTION_UP", "YAC_UP", "QUICK_GAME_UP", "RB_RECEIVING_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "up",
      PASSING_YARDS: "neutral/up",
      RECEPTIONS: "up",
      RECEIVING_YARDS: "up for YAC roles",
      RUSHING_ATTEMPTS: "mildly up",
      RUSHING_YARDS: "mildly up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Same larger team identity but new offensive tendencies; moderate uncertainty.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  TB: {
    team: "TB",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 68,
      offensivePlayCallerChangeScore: 80,
      defensivePlayCallerChangeScore: 0,
      teamTendencyTrustScore: 58,
      offensiveIdentityShiftScore: 45,
      defensiveIdentityShiftScore: 5,
      playCallerConfidenceScore: 88,
      coachingUncertaintyPenalty: 28,
    },
    notes: ["Moderate continuity; do not over-penalize prior-year tendencies."],
    offenseDeltas: ["PLAY_ACTION_UP", "EFFICIENCY_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "up",
      PASSING_YARDS: "up/neutral",
      RECEPTIONS: "neutral/up",
      RECEIVING_YARDS: "up/neutral",
      RUSHING_ATTEMPTS: "mildly up",
      RUSHING_YARDS: "mildly up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Moderate continuity; do not over-penalize prior-year tendencies."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  WAS: {
    team: "WAS",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 42,
      offensivePlayCallerChangeScore: 88,
      defensivePlayCallerChangeScore: 86,
      teamTendencyTrustScore: 38,
      offensiveIdentityShiftScore: 60,
      defensiveIdentityShiftScore: 70,
      playCallerConfidenceScore: 72,
      coachingUncertaintyPenalty: 52,
    },
    notes: ["Play-caller confidence is only moderate; thin edges should be downgraded."],
    offenseDeltas: [
      "UNDER_CENTER_UP",
      "PLAY_ACTION_UP",
      "KEEPER_ACTION_UP",
      "SHOTGUN_DOWN",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral/down",
      PASSING_COMPLETIONS: "neutral",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "neutral",
      RECEIVING_YARDS: "neutral",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Play-caller confidence is only moderate; thin edges should be downgraded."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  PHI: {
    team: "PHI",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 60,
      offensivePlayCallerChangeScore: 85,
      defensivePlayCallerChangeScore: 0,
      teamTendencyTrustScore: 50,
      offensiveIdentityShiftScore: 58,
      defensiveIdentityShiftScore: 5,
      playCallerConfidenceScore: 75,
      coachingUncertaintyPenalty: 35,
    },
    notes: ["Blend old identity and new run/play-action structure; do not overreact early."],
    offenseDeltas: [
      "OUTSIDE_ZONE_UP",
      "PLAY_ACTION_UP",
      "BOOT_UP",
      "BLEND_OLD_AND_NEW",
    ],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "up",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "neutral/up",
      RECEIVING_YARDS: "neutral",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Blend old identity and new run/play-action structure; do not overreact early."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  SEA: {
    team: "SEA",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 78,
      offensivePlayCallerChangeScore: 55,
      defensivePlayCallerChangeScore: 0,
      teamTendencyTrustScore: 70,
      offensiveIdentityShiftScore: 25,
      defensiveIdentityShiftScore: 0,
      playCallerConfidenceScore: 70,
      coachingUncertaintyPenalty: 20,
    },
    notes: ["Continuity profile; title changes should not force large projection movement."],
    offenseDeltas: ["CONTINUITY_PRIORITY", "KUBIAK_FOUNDATION_MAINTAINED"],
    defenseDeltas: [],
    propImpacts: { ...NEUTRAL_IMPACTS },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Continuity profile; title changes should not force large projection movement."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  DET: {
    team: "DET",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 74,
      offensivePlayCallerChangeScore: 82,
      defensivePlayCallerChangeScore: 0,
      teamTendencyTrustScore: 62,
      offensiveIdentityShiftScore: 50,
      defensiveIdentityShiftScore: 0,
      playCallerConfidenceScore: 87,
      coachingUncertaintyPenalty: 26,
    },
    notes: ["Moderate staff change but strong offensive continuity; do not over-penalize."],
    offenseDeltas: ["UNDER_CENTER_SLIGHT_UP", "RUN_EMPHASIS_SLIGHT_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral/slightly down",
      PASSING_COMPLETIONS: "neutral",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "neutral",
      RECEIVING_YARDS: "neutral",
      RUSHING_ATTEMPTS: "up",
      RUSHING_YARDS: "up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Moderate staff change but strong offensive continuity; do not over-penalize."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  NYJ: {
    team: "NYJ",
    season: 2026,
    blendProfile: "new_oc_same_hc",
    scores: {
      coachingContinuityScore: 62,
      offensivePlayCallerChangeScore: 85,
      defensivePlayCallerChangeScore: 65,
      teamTendencyTrustScore: 50,
      offensiveIdentityShiftScore: 55,
      defensiveIdentityShiftScore: 45,
      playCallerConfidenceScore: 80,
      coachingUncertaintyPenalty: 38,
    },
    notes: ["Moderate shift; use coach context as support, not automatic qualifier."],
    offenseDeltas: ["UNDER_CENTER_UP", "STRUCTURE_UP", "TE_RB_TARGET_FLOOR_UP"],
    defenseDeltas: [],
    propImpacts: {
      PASSING_ATTEMPTS: "neutral",
      PASSING_COMPLETIONS: "up/slight",
      PASSING_YARDS: "neutral",
      RECEPTIONS: "up for TE/RB",
      RECEIVING_YARDS: "neutral/up for TE/RB",
      RUSHING_ATTEMPTS: "neutral/up",
      RUSHING_YARDS: "neutral/up",
    },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Moderate shift; use coach context as support, not automatic qualifier."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  GB: {
    team: "GB",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 70,
      offensivePlayCallerChangeScore: 0,
      defensivePlayCallerChangeScore: 82,
      teamTendencyTrustScore: 62,
      offensiveIdentityShiftScore: 5,
      defensiveIdentityShiftScore: 60,
      playCallerConfidenceScore: 92,
      coachingUncertaintyPenalty: 22,
    },
    notes: [
      "Defensive transition should mostly affect opponent prop matchup layer, not own offense.",
    ],
    offenseDeltas: [],
    defenseDeltas: [
      "NEW_SYSTEM",
      "SPLIT_SAFETY_UP",
      "EXPLOSIVE_PASS_SUPPRESSION_UP",
    ],
    propImpacts: { ...NEUTRAL_IMPACTS },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Defensive transition should mostly affect opponent prop matchup layer, not own offense.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  DAL: {
    team: "DAL",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 58,
      offensivePlayCallerChangeScore: 0,
      defensivePlayCallerChangeScore: 85,
      teamTendencyTrustScore: 52,
      offensiveIdentityShiftScore: 0,
      defensiveIdentityShiftScore: 70,
      playCallerConfidenceScore: 88,
      coachingUncertaintyPenalty: 26,
    },
    notes: [
      "Defensive transition should mostly affect opponent prop matchup layer.",
    ],
    offenseDeltas: [],
    defenseDeltas: ["BASE_LOOK_CHANGE", "SECONDARY_RULES_CHANGE"],
    propImpacts: { ...NEUTRAL_IMPACTS },
    sourceConfidence: "MEDIUM",
    assumptionNotes: [
      "Defensive transition should mostly affect opponent prop matchup layer.",
    ],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
  NE: {
    team: "NE",
    season: 2026,
    blendProfile: "high_continuity",
    scores: {
      coachingContinuityScore: 76,
      offensivePlayCallerChangeScore: 0,
      defensivePlayCallerChangeScore: 45,
      teamTendencyTrustScore: 68,
      offensiveIdentityShiftScore: 0,
      defensiveIdentityShiftScore: 20,
      playCallerConfidenceScore: 85,
      coachingUncertaintyPenalty: 18,
    },
    notes: [
      "Title change overstates real defensive change; keep offense stable.",
    ],
    offenseDeltas: [],
    defenseDeltas: [],
    propImpacts: { ...NEUTRAL_IMPACTS },
    sourceConfidence: "MEDIUM",
    assumptionNotes: ["Do not treat title changes as automatic scheme changes."],
    lastVerified: "2026-05-19",
    appliesToWeeks: "Weeks 1-8",
  },
};

export function getTeamCoachingTransition(team: string): TeamCoachingTransition {
  return TEAM_COACHING_TRANSITIONS[team] ?? {
    ...UNCHANGED_STAFF_DEFAULT,
    team,
  };
}
