/**
 * Static fixture data for the experimental Game Edge model.
 *
 * 12 games hand-tuned to demonstrate each of the recommendation
 * paths (Strong ML / Playable ML / Upset Watch / Spread Value /
 * Cover Watch / Pass — No Edge / Pass — Too Much Uncertainty).
 *
 * No real data, no APIs. Each fixture documents the scenario it
 * exercises in its `scenarioNote` field so reviewers can map
 * fixture → recommendation path.
 */

import type { GameEdgeInput } from "./game-edge-types";

export interface GameEdgeFixture extends GameEdgeInput {
  scenarioNote: string;
}

export const GAME_EDGE_FIXTURES: GameEdgeFixture[] = [
  // 1. Underdog pass-rush advantage + favorite QB pressure-sensitive.
  {
    scenarioNote:
      "Underdog has strong pass-rush advantage and the favorite QB is pressure-sensitive — upset watch / playable underdog ML",
    gameId: "fixture-ge-001-pit-at-buf",
    season: 2025,
    week: 12,
    homeTeam: "BUF",
    awayTeam: "PIT",
    homeMoneylineOdds: -260,
    awayMoneylineOdds: 215,
    homeSpread: -6.5,
    awaySpread: 6.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.71,
    marketAwayWinProbability: 0.29,
    gameTotal: 44.5,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 18,
    coachingUncertaintyAway: 20,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.78,
    awayOffensiveContinuityScore: 0.72,
    homeDefensiveContinuityScore: 0.75,
    awayDefensiveContinuityScore: 0.85,
    homeQBStabilityScore: 0.42,
    awayQBStabilityScore: 0.65,
    homePressureAdvantageScore: 0.45,
    awayPressureAdvantageScore: 0.78,
    homeRunGameAdvantageScore: 0.55,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.55,
    awayPassGameAdvantageScore: 0.5,
    homeInjuryRiskScore: 0.65,
    awayInjuryRiskScore: 0.78,
  },
  // 2. Weather compression + strong underdog run game.
  {
    scenarioNote:
      "Heavy weather + underdog with run-game edge — weather compresses scoring, upset compression favors dog",
    gameId: "fixture-ge-002-bal-at-cle",
    season: 2025,
    week: 14,
    homeTeam: "CLE",
    awayTeam: "BAL",
    homeMoneylineOdds: 195,
    awayMoneylineOdds: -240,
    homeSpread: 5.5,
    awaySpread: -5.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.32,
    marketAwayWinProbability: 0.68,
    gameTotal: 39,
    weatherRiskScore: 0.4,
    coachingUncertaintyHome: 18,
    coachingUncertaintyAway: 20,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.7,
    awayOffensiveContinuityScore: 0.85,
    homeDefensiveContinuityScore: 0.8,
    awayDefensiveContinuityScore: 0.8,
    homeQBStabilityScore: 0.6,
    awayQBStabilityScore: 0.8,
    homePressureAdvantageScore: 0.55,
    awayPressureAdvantageScore: 0.5,
    homeRunGameAdvantageScore: 0.72,
    awayRunGameAdvantageScore: 0.5,
    homePassGameAdvantageScore: 0.42,
    awayPassGameAdvantageScore: 0.62,
    homeInjuryRiskScore: 0.75,
    awayInjuryRiskScore: 0.75,
  },
  // 3. Favorite clear edge but ML price too expensive → spread or pass.
  {
    scenarioNote:
      "Favorite clearly better but ML priced at -650, way past any edge the model could justify — spread or PASS",
    gameId: "fixture-ge-003-was-at-phi",
    season: 2025,
    week: 7,
    homeTeam: "PHI",
    awayTeam: "WAS",
    homeMoneylineOdds: -650,
    awayMoneylineOdds: 460,
    homeSpread: -12.5,
    awaySpread: 12.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.87,
    marketAwayWinProbability: 0.13,
    gameTotal: 48,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 30,
    coachingUncertaintyAway: 38,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.72,
    awayOffensiveContinuityScore: 0.62,
    homeDefensiveContinuityScore: 0.7,
    awayDefensiveContinuityScore: 0.62,
    homeQBStabilityScore: 0.72,
    awayQBStabilityScore: 0.62,
    homePressureAdvantageScore: 0.58,
    awayPressureAdvantageScore: 0.5,
    homeRunGameAdvantageScore: 0.6,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.6,
    awayPassGameAdvantageScore: 0.55,
    homeInjuryRiskScore: 0.78,
    awayInjuryRiskScore: 0.72,
  },
  // 4. Spread value on dog but not ML.
  {
    scenarioNote:
      "Spread cover edge on the underdog but ML price doesn't clear the dog threshold",
    gameId: "fixture-ge-004-cin-at-bal",
    season: 2025,
    week: 11,
    homeTeam: "BAL",
    awayTeam: "CIN",
    homeMoneylineOdds: -200,
    awayMoneylineOdds: 170,
    homeSpread: -4.5,
    awaySpread: 4.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.66,
    marketAwayWinProbability: 0.34,
    gameTotal: 47,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 20,
    coachingUncertaintyAway: 22,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.8,
    awayOffensiveContinuityScore: 0.78,
    homeDefensiveContinuityScore: 0.78,
    awayDefensiveContinuityScore: 0.72,
    homeQBStabilityScore: 0.7,
    awayQBStabilityScore: 0.7,
    homePressureAdvantageScore: 0.55,
    awayPressureAdvantageScore: 0.62,
    homeRunGameAdvantageScore: 0.62,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.5,
    awayPassGameAdvantageScore: 0.6,
    homeInjuryRiskScore: 0.78,
    awayInjuryRiskScore: 0.78,
  },
  // 5. Spread value on favorite but not ML.
  {
    scenarioNote:
      "Favorite covers reliably but the ML is too expensive — spread value, not ML",
    gameId: "fixture-ge-005-nyg-at-sf",
    season: 2025,
    week: 8,
    homeTeam: "SF",
    awayTeam: "NYG",
    homeMoneylineOdds: -420,
    awayMoneylineOdds: 340,
    homeSpread: -9,
    awaySpread: 9,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.81,
    marketAwayWinProbability: 0.19,
    gameTotal: 44,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 22,
    coachingUncertaintyAway: 70,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.85,
    awayOffensiveContinuityScore: 0.45,
    homeDefensiveContinuityScore: 0.85,
    awayDefensiveContinuityScore: 0.5,
    homeQBStabilityScore: 0.85,
    awayQBStabilityScore: 0.5,
    homePressureAdvantageScore: 0.78,
    awayPressureAdvantageScore: 0.45,
    homeRunGameAdvantageScore: 0.75,
    awayRunGameAdvantageScore: 0.45,
    homePassGameAdvantageScore: 0.78,
    awayPassGameAdvantageScore: 0.42,
    homeInjuryRiskScore: 0.78,
    awayInjuryRiskScore: 0.62,
  },
  // 6. High upset score but low data quality → PASS.
  {
    scenarioNote:
      "Lots of dog-friendly signals but data quality too low — model is unreliable, PASS",
    gameId: "fixture-ge-006-lar-at-sea",
    season: 2025,
    week: 4,
    homeTeam: "SEA",
    awayTeam: "LAR",
    homeMoneylineOdds: 220,
    awayMoneylineOdds: -260,
    homeSpread: 6,
    awaySpread: -6,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.31,
    marketAwayWinProbability: 0.69,
    gameTotal: 41,
    weatherRiskScore: 0.5,
    coachingUncertaintyHome: 65,
    coachingUncertaintyAway: 28,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.25,
    awayOffensiveContinuityScore: 0.35,
    homeDefensiveContinuityScore: 0.3,
    awayDefensiveContinuityScore: 0.4,
    homeQBStabilityScore: 0.42,
    awayQBStabilityScore: 0.55,
    homePressureAdvantageScore: 0.7,
    awayPressureAdvantageScore: 0.45,
    homeRunGameAdvantageScore: 0.62,
    awayRunGameAdvantageScore: 0.5,
    homePassGameAdvantageScore: 0.45,
    awayPassGameAdvantageScore: 0.55,
    homeInjuryRiskScore: 0.55,
    awayInjuryRiskScore: 0.65,
    gameDataQualityScore: 0.32,
  },
  // 7. Coaching uncertainty on favorite → upset watch on dog.
  {
    scenarioNote:
      "Favorite has serious coaching transition uncertainty — upset watch on home dog",
    gameId: "fixture-ge-007-nyj-at-mia",
    season: 2025,
    week: 6,
    homeTeam: "NYJ",
    awayTeam: "MIA",
    homeMoneylineOdds: 145,
    awayMoneylineOdds: -170,
    homeSpread: 3,
    awaySpread: -3,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.4,
    marketAwayWinProbability: 0.6,
    gameTotal: 42,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 24,
    coachingUncertaintyAway: 72,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.7,
    awayOffensiveContinuityScore: 0.45,
    homeDefensiveContinuityScore: 0.75,
    awayDefensiveContinuityScore: 0.55,
    homeQBStabilityScore: 0.7,
    awayQBStabilityScore: 0.55,
    homePressureAdvantageScore: 0.6,
    awayPressureAdvantageScore: 0.55,
    homeRunGameAdvantageScore: 0.6,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.55,
    awayPassGameAdvantageScore: 0.55,
    homeInjuryRiskScore: 0.72,
    awayInjuryRiskScore: 0.65,
  },
  // 8. Injury risk on dog blocks play.
  {
    scenarioNote:
      "Underdog has serious injury risk — blocks upset play, PASS",
    gameId: "fixture-ge-008-car-at-tb",
    season: 2025,
    week: 9,
    homeTeam: "TB",
    awayTeam: "CAR",
    homeMoneylineOdds: -340,
    awayMoneylineOdds: 280,
    homeSpread: -7.5,
    awaySpread: 7.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.78,
    marketAwayWinProbability: 0.22,
    gameTotal: 46,
    weatherRiskScore: 0.65,
    coachingUncertaintyHome: 28,
    coachingUncertaintyAway: 30,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.78,
    awayOffensiveContinuityScore: 0.62,
    homeDefensiveContinuityScore: 0.78,
    awayDefensiveContinuityScore: 0.68,
    homeQBStabilityScore: 0.8,
    awayQBStabilityScore: 0.6,
    homePressureAdvantageScore: 0.62,
    awayPressureAdvantageScore: 0.68,
    homeRunGameAdvantageScore: 0.6,
    awayRunGameAdvantageScore: 0.4,
    homePassGameAdvantageScore: 0.6,
    awayPassGameAdvantageScore: 0.45,
    homeInjuryRiskScore: 0.75,
    awayInjuryRiskScore: 0.35,
  },
  // 9. Large spread with backdoor cover risk.
  {
    scenarioNote:
      "Big -13.5 favorite spread with backdoor cover risk — Cover Watch / PASS",
    gameId: "fixture-ge-009-chi-at-det",
    season: 2025,
    week: 13,
    homeTeam: "DET",
    awayTeam: "CHI",
    homeMoneylineOdds: -550,
    awayMoneylineOdds: 400,
    homeSpread: -13.5,
    awaySpread: 13.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.85,
    marketAwayWinProbability: 0.15,
    gameTotal: 49,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 25,
    coachingUncertaintyAway: 40,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.85,
    awayOffensiveContinuityScore: 0.6,
    homeDefensiveContinuityScore: 0.78,
    awayDefensiveContinuityScore: 0.6,
    homeQBStabilityScore: 0.85,
    awayQBStabilityScore: 0.62,
    homePressureAdvantageScore: 0.72,
    awayPressureAdvantageScore: 0.5,
    homeRunGameAdvantageScore: 0.7,
    awayRunGameAdvantageScore: 0.5,
    homePassGameAdvantageScore: 0.78,
    awayPassGameAdvantageScore: 0.5,
    homeInjuryRiskScore: 0.75,
    awayInjuryRiskScore: 0.7,
  },
  // 10. Key number spread fragility.
  {
    scenarioNote:
      "Spread sits on the -3 key number — even with a small edge, fragility forces caution",
    gameId: "fixture-ge-010-gb-at-min",
    season: 2025,
    week: 10,
    homeTeam: "MIN",
    awayTeam: "GB",
    homeMoneylineOdds: -150,
    awayMoneylineOdds: 130,
    homeSpread: -3,
    awaySpread: 3,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.58,
    marketAwayWinProbability: 0.42,
    gameTotal: 46,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 22,
    coachingUncertaintyAway: 22,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.78,
    awayOffensiveContinuityScore: 0.78,
    homeDefensiveContinuityScore: 0.7,
    awayDefensiveContinuityScore: 0.7,
    homeQBStabilityScore: 0.75,
    awayQBStabilityScore: 0.75,
    homePressureAdvantageScore: 0.55,
    awayPressureAdvantageScore: 0.6,
    homeRunGameAdvantageScore: 0.58,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.55,
    awayPassGameAdvantageScore: 0.55,
    homeInjuryRiskScore: 0.75,
    awayInjuryRiskScore: 0.75,
  },
  // 11. Dome / high total — upset compression weakens.
  {
    scenarioNote:
      "Dome game with 53-total — possessions inflate, dog compression weakens, upset score drops",
    gameId: "fixture-ge-011-mia-at-buf",
    season: 2025,
    week: 15,
    homeTeam: "BUF",
    awayTeam: "MIA",
    homeMoneylineOdds: -210,
    awayMoneylineOdds: 175,
    homeSpread: -5.5,
    awaySpread: 5.5,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.66,
    marketAwayWinProbability: 0.34,
    gameTotal: 53.5,
    weatherRiskScore: 1.0,
    coachingUncertaintyHome: 18,
    coachingUncertaintyAway: 75,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.78,
    awayOffensiveContinuityScore: 0.5,
    homeDefensiveContinuityScore: 0.75,
    awayDefensiveContinuityScore: 0.6,
    homeQBStabilityScore: 0.85,
    awayQBStabilityScore: 0.6,
    homePressureAdvantageScore: 0.55,
    awayPressureAdvantageScore: 0.62,
    homeRunGameAdvantageScore: 0.55,
    awayRunGameAdvantageScore: 0.45,
    homePassGameAdvantageScore: 0.65,
    awayPassGameAdvantageScore: 0.6,
    homeInjuryRiskScore: 0.78,
    awayInjuryRiskScore: 0.7,
  },
  // 12. Neutral game with no edge.
  {
    scenarioNote:
      "Coin-flip game with no edge on either side — Pass / No Edge",
    gameId: "fixture-ge-012-tex-at-jax",
    season: 2025,
    week: 5,
    homeTeam: "JAX",
    awayTeam: "TEX",
    homeMoneylineOdds: -115,
    awayMoneylineOdds: -105,
    homeSpread: -1,
    awaySpread: 1,
    homeSpreadOdds: -110,
    awaySpreadOdds: -110,
    marketHomeWinProbability: 0.52,
    marketAwayWinProbability: 0.48,
    gameTotal: 46,
    weatherRiskScore: 0.85,
    coachingUncertaintyHome: 20,
    coachingUncertaintyAway: 20,
    homeRestDays: 7,
    awayRestDays: 7,
    homeOffensiveContinuityScore: 0.75,
    awayOffensiveContinuityScore: 0.75,
    homeDefensiveContinuityScore: 0.75,
    awayDefensiveContinuityScore: 0.75,
    homeQBStabilityScore: 0.75,
    awayQBStabilityScore: 0.75,
    homePressureAdvantageScore: 0.55,
    awayPressureAdvantageScore: 0.55,
    homeRunGameAdvantageScore: 0.55,
    awayRunGameAdvantageScore: 0.55,
    homePassGameAdvantageScore: 0.55,
    awayPassGameAdvantageScore: 0.55,
    homeInjuryRiskScore: 0.78,
    awayInjuryRiskScore: 0.78,
  },
];

export function getGameEdgeFixtureById(
  gameId: string,
): GameEdgeFixture | undefined {
  return GAME_EDGE_FIXTURES.find((g) => g.gameId === gameId);
}
