/**
 * Server-side helper to surface the latest V1 vs V2 backtest
 * comparison summary on the /backtest page.
 *
 * Reads from `data/backtests/2025/v1-v2-comparison.fixture.json`
 * and `data/backtests/2025/recommendation-changes.fixture.json`
 * when they exist (generated by
 * `npx tsx scripts/run-backtest-2025.ts --fixtures --algorithm-mode compare`).
 *
 * Never calls any external service. Pure file IO.
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.join(process.cwd(), "data", "backtests", "2025");

export interface FixtureComparisonSummary {
  generatedAt: string;
  scope: {
    season: number;
    startWeek: number;
    endWeek: number;
    propTypes: string[];
  };
  v1: {
    evaluated: number;
    qualifiedBets: number;
    hitRate: number;
    roiPct: number;
    profitUnits: number;
  };
  v2: {
    evaluated: number;
    qualifiedBets: number;
    hitRate: number;
    roiPct: number;
    profitUnits: number;
  };
  deltaSummary: {
    evaluatedDelta: number;
    qualifiedBetsDelta: number;
    hitRateDelta: number;
    roiPctDelta: number;
    profitUnitsDelta: number;
    v2AverageConfidenceAdjustedEdge: number;
  };
}

export interface FixtureRecommendationChanges {
  generatedAt: string;
  totalEvaluated: number;
  counts: Record<string, number>;
  v1OnlyBets: number;
  v2OnlyBets: number;
  oppositeSides: number;
  topNewV2Disqualifiers: Array<{ disqualifier: string; count: number }>;
}

export function loadFixtureComparisonSummary():
  | FixtureComparisonSummary
  | undefined {
  const p = path.join(ROOT, "v1-v2-comparison.fixture.json");
  if (!fs.existsSync(p)) return undefined;
  try {
    return JSON.parse(fs.readFileSync(p, "utf8")) as FixtureComparisonSummary;
  } catch {
    return undefined;
  }
}

export function loadFixtureRecommendationChanges():
  | FixtureRecommendationChanges
  | undefined {
  const p = path.join(ROOT, "recommendation-changes.fixture.json");
  if (!fs.existsSync(p)) return undefined;
  try {
    return JSON.parse(
      fs.readFileSync(p, "utf8"),
    ) as FixtureRecommendationChanges;
  } catch {
    return undefined;
  }
}
